import numpy as np
import pandas as pd


def make_trend(
        series_len,
        rw_loc=0.0,
        rw_scale=0.1,
        seed=1
):
    """Module to generate time-series trend with different methods
    Parameters
    ----------
    series_len: int
        Total length of series
    rw_loc: float
        Location parameter of random walk generated by `np.random.normal()`
    rw_scale: float
        Scale parameter of random walk generated by `np.random.normal()`
    seed: int
        Seed passed into `np.random.default_rng()`
    Returns
    -------
    np.array-llike
        Simulated trend with length equals `series_len`

    """
    # make trend
    rw = np.random.default_rng(seed).normal(rw_loc, rw_scale, series_len)
    trend = np.cumsum(rw)

    return trend
